{% set name = "gwollum" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.ligo.org/virgo/virgoapp/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ab020f71fecaf53eb909e498ced047996cc5d1d7541c7333ae2cac696fee54b

build:
  error_overdepending: true
  error_overlinking: true
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("gwollum", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.12.0
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - fftw
    - hdf5
    - libframel >=8.40.5
    - root_base
  run:
    - fftw
    - hdf5
    - libframel
    - root_base
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  requires:
    - pkg-config
  commands:
    # run test commands
    - for gwltest in ${PREFIX}/sbin/gwl-test-*; do ${gwltest}; done  # [linux]
    # check pkg-config
    - pkg-config --print-errors --exact-version {{ version }} {{ name }}

about:
  home: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  doc_url: https://virgo.docs.ligo.org/virgoapp/{{ name }}/
  dev_url: https://git.ligo.org/virgo/virgoapp/{{ name }}.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Tools for gravitational-wave analyses
  description: |
    The GWOLLUM package contains a set of software tools designed to perform
    GW analyses.  Most of the code source is written with the C++ language
    and it also heavily relies on the CERN ROOT libraries (also C++).

extra:
  recipe-maintainers:
    - duncanmmacleod
    - rhyspoulton
